export const airLineData = [
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "20110",
    dateOfTravel: "Sep 5, 2021",
    airline: "Qatar Airways",
    id: 1,
  },
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "520000",
    dateOfTravel: "Jun 22, 2022",
    airline: "Qatar Airways",
    id: 2,
  },
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "92400",
    dateOfTravel: "Jan 20, 2023",
    airline: "Qatar Airways",
    id: 3,
  },
  {
    logo: "https://airhex.com/images/airline-logos/alt/emirates.png",
    price: "440000",
    dateOfTravel: "Dec 3, 2020",
    airline: "Emirates",
    id: 4,
  },
  {
    logo: "https://airhex.com/images/airline-logos/alt/emirates.png",
    price: "20000",
    dateOfTravel: "Aug 19, 2022",
    airline: "Emirates",
    id: 5,
  },
  {
    logo: "https://airhex.com/images/airline-logos/alt/emirates.png",
    price: "23000",
    dateOfTravel: "May 11, 2022",
    airline: "Emirates",
    id: 6,
  },
  {
    logo: "https://e7.pngegg.com/pngimages/698/786/png-clipart-brand-logo-product-design-trademark-korean-air-blue-text.png",
    price: "99200",
    dateOfTravel: "Aug 16, 2022",
    airline: "Korean Air",
    id: 7,
  },
  {
    logo: "https://e7.pngegg.com/pngimages/698/786/png-clipart-brand-logo-product-design-trademark-korean-air-blue-text.png",
    price: "47800",
    dateOfTravel: "Feb 10, 2023",
    airline: "Korean Air",
    id: 8,
  },
  {
    logo: "https://e7.pngegg.com/pngimages/698/786/png-clipart-brand-logo-product-design-trademark-korean-air-blue-text.png",
    price: "35600",
    dateOfTravel: "Aug 26, 2018",
    airline: "Korean Air",
    id: 9,
  },
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "99000",
    dateOfTravel: "Mar 22, 2023",
    airline: "Qatar Airways",
    id: 10,
  },
];
