export const airLineData = [
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "20110",
    dateOfTravel: "01-04-2023 ",
    airline: "Qatar Airways",
    id: 1,
  },
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "520000",
    dateOfTravel: "01-01-2023 ",
    airline: "Qatar Airways",
    id: 2,
  },
  {
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png",
    price: "92400",
    dateOfTravel: "01-06-2023 ",
    airline: "Qatar Airways",
    id: 3,
  },
  {
    logo: "https://airhex.com/images/airline-logos/alt/emirates.png",
    price: "440000",
    dateOfTravel: "01-02-2023 ",
    airline: "Emirates",
    id: 4,
  },
  {
    logo: "https://airhex.com/images/airline-logos/alt/emirates.png",
    price: "20000",
    dateOfTravel: "01-06-2023 ",
    airline: "Emirates",
    id: 5,
  },
  {
    logo: "https://airhex.com/images/airline-logos/alt/emirates.png",
    price: "23000",
    dateOfTravel: "01-02-2023 ",
    airline: "Emirates",
    id: 6,
  },
  {
    logo: "https://e7.pngegg.com/pngimages/698/786/png-clipart-brand-logo-product-design-trademark-korean-air-blue-text.png",
    price: "99200",
    dateOfTravel: "01-03-2023 ",
    airline: "Korean Air",
    id: 7,
  },
  {
    logo: "https://e7.pngegg.com/pngimages/698/786/png-clipart-brand-logo-product-design-trademark-korean-air-blue-text.png",
    price: "47800",
    dateOfTravel: "01-06-2023 ",
    airline: "Korean Air",
    id: 8,
  },
  {
    logo: "https://e7.pngegg.com/pngimages/698/786/png-clipart-brand-logo-product-design-trademark-korean-air-blue-text.png",
    price: "35600",
    dateOfTravel: "01-04-2023 ",
    airline: "Korean Air",
    id: 9,
  },
];
